# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RocketApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RocketApp

pod 'Moya/RxSwift', '~> 14.0'             # network abstraction
pod 'Action', '~> 4.0'                # observable abstraction
pod 'RxSwiftExt', '~> 5.2'
pod 'SDWebImage', '~> 5.0'
pod 'SwiftyJSON', '~> 5.0'                # JSON-Data parsing convenience
pod 'EZProgressHUD', '~> 1.5.3'

end
